routes/web.php
<?php

use App\Http\Controllers\ApprovalQuoteController;
use App\Http\Controllers\Auth\EmailVerificationController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\CustomerQuoteController;
use App\Http\Controllers\CustomerQuotePDFController;
use App\Http\Controllers\OrderPDFController;
use App\Http\Controllers\QuotePDFController;
use App\Http\Livewire\Auth\Login;
use App\Http\Livewire\Auth\Passwords\Confirm;
use App\Http\Livewire\Auth\Passwords\Email;
use App\Http\Livewire\Auth\Passwords\Reset;
use App\Http\Livewire\Auth\Register;
use App\Http\Livewire\Auth\Verify;
use App\Http\Livewire\CustomerQuotes;
use App\Http\Livewire\Customers;
use App\Http\Livewire\Dashboard;
use App\Http\Livewire\Orders;
use App\Http\Livewire\ProductDiscounts;
use App\Http\Livewire\Profile;
use App\Http\Livewire\Quotes;
use App\Http\Livewire\Tenants;
use App\Http\Livewire\Users;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::redirect('/', 'dashboard');

Route::middleware('guest')->group(function () {
    Route::get('login', Login::class)
        ->name('login');

//    Route::get('register', Register::class)
//        ->name('register');
});

Route::get('password/reset', Email::class)
    ->name('password.request');

Route::get('password/reset/{token}', Reset::class)
    ->name('password.reset');

Route::middleware('auth')->group(function () {
    Route::get('email/verify', Verify::class)
        ->middleware('throttle:6,1')
        ->name('verification.notice');

    Route::get('password/confirm', Confirm::class)
        ->name('password.confirm');
});

Route::get('/customer-quotes/{customerQuote}', [CustomerQuoteController::class, 'show'])
    ->whereNumber('customerQuote')->name('customer-quotes.show');

Route::get('/customer-quotes/{customerQuote}/approve', [ApprovalQuoteController::class, 'store'])
    ->whereNumber('customerQuote')->name('customer-quotes.approve');

Route::get('customer-quotes/{customerQuote}.pdf', CustomerQuotePDFController::class)
    ->name('customer-quotes.pdf');

Route::middleware('auth')->group(function () {
    Route::get('/', Dashboard::class)->name('home');
    Route::get('/orders', Orders::class)->name('orders');
    Route::get('/quotes', Quotes::class)->name('quotes');
    Route::get('/users', Users::class)->name('users');
    Route::get('/tenants', Tenants::class)->name('tenants');
    Route::get('/customers', Customers::class)->name('customers');
    Route::get('/customer-quotes', CustomerQuotes::class)->name('customer-quotes');
    Route::get('/product-discounts', ProductDiscounts::class)->name('product-discounts');
    Route::get('/profile', Profile::class)->name('profile');

    Route::get('email/verify/{id}/{hash}', EmailVerificationController::class)
        ->middleware('signed')
        ->name('verification.verify');

    Route::get('logout', LogoutController::class)
        ->name('logout');

    Route::get('quotes/{quote}', QuotePDFController::class)
        ->name('quote.pdf');

    Route::get('orders/{order}', OrderPDFController::class)
        ->name('order.pdf');
});

app/Models/Customer.php
<?php

namespace App\Models;

use App\Traits\BelongsToTenant;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    use HasFactory, BelongsToTenant;

    protected $guarded = [];

    public function quotes()
    {
        return $this->hasMany(CustomerQuote::class);
    }

    public function getLocationAttribute()
    {
        return "{$this->city} {$this->state} {$this->postcode}";
    }
}

app/Models/Order.php
<?php

namespace App\Models;

use App\Scopes\TenantScope;
use App\Traits\BelongsToTenant;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class Order extends Model
{
    use SoftDeletes, HasFactory, BelongsToTenant;

    const STATUS_ORDERED = 'ordered';
    const STATUS_CONFIRMED = 'confirmed';
    const STATUS_MANUFACTURING = 'manufacturing';
    const STATUS_COMPLETED = 'completed';

    const STATUSES = [
        self::STATUS_ORDERED => 'Ordered',
        self::STATUS_CONFIRMED => 'Confirmed',
        self::STATUS_MANUFACTURING => 'Manufacturing',
        self::STATUS_COMPLETED => 'Completed'
    ];

    protected $casts = ['eta' => 'date'];

    protected $appends = ['eta_for_editing'];

    protected $guarded = [];

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
        $this->status = self::STATUS_ORDERED;
    }

    public function items()
    {
        return $this->hasMany(OrderItem::class);
    }

    public function invoice()
    {
        return $this->hasOne(Invoice::class);
    }

    public function quote()
    {
        return $this->belongsTo(Quote::class);
    }

    public function tenant()
    {
        return $this->belongsTo(Tenant::class);
    }

    public function shippingAddress()
    {
        return $this->belongsTo(Address::class);
    }

    public function billingAddress()
    {
        return $this->belongsTo(Address::class);
    }

    public function staff()
    {
        return $this->belongsTo(User::class, 'staff_id');
    }

    public function complete()
    {
        $this->update(['status' => Order::STATUS_COMPLETED]);
    }

    public function confirm()
    {
        $this->update(['status' => Order::STATUS_CONFIRMED]);
    }

    public function getStatusColourAttribute(): string
    {
        return [
            self::STATUS_ORDERED => 'indigo'
        ][$this->status] ?? 'cool-gray';
    }

    public function getDateForHumansAttribute()
    {
        return $this->created_at->diffForHumans();
    }

    /**
     * @param Quote $quote
     *
     * @throws \Exception
     */
    public static function createFromQuote(Quote $quote)
    {
        foreach ([
            BasswoodShutter::class,
            PvcShutter::class,
            AuPvcShutter::class,
            AluminiumShutter::class,
            RollerBlind::class
        ] as $productClass) {
            try {
                $products = $quote->getProductCollection($productClass)->all();
                if (!empty($products)) {
                    DB::beginTransaction();
                    if ($customerQuote = $quote->customerQuote) {
                        $totalItems = $quote->items->count();
                        if ($customerQuote->markup_type == CustomerQuote::MARKUP_FIXED) {
                            $fixedMarkup = $customerQuote->markup_value / $totalItems;
                        } else {
                            $percentMarkup = $customerQuote->markup_value;
                        }
                    }

                    $order = Order::make([
                        'reference'  => $quote->reference,
                        'notes'         => $quote->notes,
                        'product'       => $productClass::NAME
                    ]);

                    $order->tenant()->associate($quote->tenant);

                    if ($billingAddress = $quote->tenant->billingAddress) {
                        $order->billingAddress()->associate($billingAddress);
                    }
                    if ($shippingAddress = $quote->tenant->shippingAddress) {
                        $order->shippingAddress()->associate($shippingAddress);
                    }

                    $items = [];
                    foreach ($products as $product) {
                        $item = OrderItem::createFromProduct($product);
                        if (isset($fixedMarkup)) {
                            $item->markup_value = $fixedMarkup;
                        } elseif (isset($percentMarkup)) {
                            $item->markup_value = $item->amount * $percentMarkup / 100;
                        }
                        $item->amount = $item->unit_price - $item->discount_value + $item->markup_value;
                        $order->amount += $item->amount;
                        $items[] = $item;
                    }
                    $order->staff()->associate(auth()->user());
                    $order->save();
                    $order->items()->saveMany($items);
                    ConvertedQuote::create([
                        'quote_id' => $quote->id,
                        'order_id' => $order->id
                    ]);
                    DB::commit();
                }
            } catch (\Exception $e) {
                DB::rollBack();
                throw $e;
            }
        }
    }

    /**
     * @param Tenant $tenant
     * @param array  $productData
     * @param string $productClass
     * @param string $reference
     * @param string $notes
     *
     * @throws \Exception
     */
    public static function createFromFormData(
        Tenant $tenant,
        array $productData,
        string $productClass,
        string $reference,
        string $notes
    ) {
        try {
            if (!empty($productData)) {
                DB::beginTransaction();
                $order = Order::make([
                    'reference'  => $reference,
                    'notes'         => $notes,
                    'product'       => $productClass::NAME
                ]);

                $order->tenant()->associate($tenant);
                $order->staff()->associate(auth()->user());
                if ($tenant->billingAddress) {
                    $order->billingAddress()->associate($tenant->billingAddress);
                }
                if ($tenant->shippingAddress) {
                    $order->shippingAddress()->associate($tenant->shippingAddress);
                }

                $items = [];
                foreach ($productData as $shutter) {
                    $item = OrderItem::createFromProduct($productClass::create($shutter));
                    $item->amount = $item->unit_price - $item->discount_value + $item->markup_value;
                    $order->amount += $item->amount;
                    $order->save();
                    $items[] = $item;
                }
                $order->items()->saveMany($items);
                DB::commit();
            }
        } catch (\Exception $e) {
            DB::rollBack();
            throw $e;
        }
    }

    public function getStatuses(): array
    {
        switch ($this->status) {
            case static::STATUS_CONFIRMED:
                return [
                    static::STATUS_CONFIRMED,
                    static::STATUS_MANUFACTURING,
                    static::STATUS_COMPLETED
                ];
            case static::STATUS_MANUFACTURING:
                return [
                    static::STATUS_MANUFACTURING,
                    static::STATUS_COMPLETED
                ];
            default:
                return [
                    static::STATUS_ORDERED,
                    static::STATUS_CONFIRMED,
                    static::STATUS_MANUFACTURING,
                    static::STATUS_COMPLETED,
                ];
        }
    }

    public function getEtaForEditingAttribute()
    {
        return optional($this->eta)->format('d/m/Y');
    }

    public function setEtaForEditingAttribute($value)
    {
        if ($value) {
            $this->eta = Carbon::createFromFormat('d/m/Y', $value);
        }
    }
}

app/Http/Livewire/AluminiumShutterForm.php
<?php

namespace App\Http\Livewire;

use App\Models\AluminiumShutter;
use Illuminate\Validation\Rule;
use Livewire\Component;

class AluminiumShutterForm extends Component
{
    public AluminiumShutter $editing;

    protected $listeners = [
        'addProduct' => 'addAluminiumShutter',
        'setProductData' => 'setProductData'
    ];

    public function rules()
    {
        return [
            'editing.name' => 'required|max:255',
            'editing.width' => 'required|integer|min:250',
            'editing.drop' => 'required|integer|max:3050|min:250',
            'editing.shutter_type' => [
                'required',
                Rule::in(
                    'Standard',
                    'Sliding',
                    'Bifold Track',
                    'U Channel'
                )
            ],
            'editing.corner' => [
                'required',
                Rule::in('No', '90', '135')
            ],
            'editing.panel_layout' => [
                'required',
                'regex:/^[C|D|L|R|T|-]+$/i'
            ],
            'editing.in_or_out' => [
                'required',
                Rule::in('In', 'Out')
            ],
            'editing.mid_rail' => [
                'required',
                Rule::in('NA', 'Centre', '1', '2')
            ],
            'editing.mid_rail_height' => [

            ],
            'editing.blade_size' => [
                'required',
                Rule::in('89mm')
            ],
            'editing.tilt_rod' => [
                'required',
                Rule::in('Clear View')
            ],
            'editing.colour' => [
                'required',
                Rule::in('White', 'Cream', 'Silver')
            ],
            'editing.frame' => [
                'required',
                Rule::in('No Frame','L', 'U Channel', 'Bi Fold')
            ],
            'editing.notes'            => [

            ]

        ];
    }

    public function mount()
    {
        $this->editing = $this->makeBlankAluminiumShutter();
    }

    private function makeBlankAluminiumShutter()
    {
        return AluminiumShutter::make([
            'shutter_type' => '',
            'corner' => '',
            'panel_layout' => '',
            'in_or_out' => '',
            'mid_rail' => '',
            'mid_rail_height' => '',
            'blade_size' => '',
            'tilt_rod' => '',
            'colour' => '',
            'frame' => '',
            'notes' => ''
        ]);
    }

    public function addAluminiumShutter()
    {
        $this->emitUp('productAdded', 'aluminium_shutters', $this->editing);
    }

    public function setProductData($productData = [])
    {
        if ($productData) {
            $this->editing = AluminiumShutter::make($productData);
        }

        $this->resetErrorBag();
    }

    public function render()
    {
        return view('livewire.aluminium-shutter-form');
    }
}

app/Http/Livewire/Customers.php
<?php

namespace App\Http\Livewire;

use App\Http\Livewire\DataTable\WithBulkActions;
use App\Http\Livewire\DataTable\WithCachedRows;
use App\Http\Livewire\DataTable\WithPerPagePagination;
use App\Http\Livewire\DataTable\WithSorting;
use App\Models\Customer;
use Livewire\Component;

class Customers extends Component
{
    use WithPerPagePagination, WithSorting, WithBulkActions, WithCachedRows;

    public bool $showEditModal = false;
    public bool $showDeleteModal = false;

    public Customer $customer;

    public array $filters = [
        'search' => '',
    ];

    public function rules()
    {
        return [
            'customer.tenant_id'    => [
                'required',
                'integer'
            ],
            'customer.name'         => [
                'required',
                'string'
            ],
            'customer.email'        => [
                'required',
                'email',
            ],
            'customer.contact_name' => [
                'required',
                'string'
            ],
            'customer.address'      => [
                'required',
                'string'
            ],
            'customer.city'         => [
                'required',
                'string'
            ],
            'customer.postcode'     => [
                'required',
                'string'
            ],
            'customer.state'        => [
                'required',
                'string'
            ],
        ];
    }

    public function getRowsQueryProperty()
    {
        $query = Customer::with('tenant')
            ->select('customers.*')
            ->join('tenants', 'tenants.id', '=', 'customers.tenant_id')
            ->when($this->filters['search'],
                fn($query, $search) => $query->where('tenants.name', 'like', '%' . $search . '%')
                    ->orWhere('customers.name', 'like', '%' . $search . '%'));

        return $this->applySorting($query);
    }

    public function getRowsProperty()
    {
        return $this->cache(function () {
            return $this->applyPagination($this->rowsQuery);
        });
    }

    public function newCustomer()
    {
        $this->customer = Customer::make(['tenant_id' => '', 'state' => '']);

        $this->showEditModal = true;
    }

    public function save()
    {
        $this->validate();

        $this->customer->save();

        $this->showEditModal = false;

        $this->notify('Customer created');
    }

    public function render()
    {
        return view('livewire.customers', [
            'customers' => $this->rows
        ]);
    }
}

resources/views/livewire/email-form.blade.php
<div class="mt-2 grid grid-cols-1 gap-y-6 gap-x-4">
{{--    <x-input.group inline for="email" label="Email" :error="$errors->first('email')">--}}
{{--        <x-input.text wire:model.defer="email" id="email" placeholder="Email"></x-input.text>--}}
{{--    </x-input.group>--}}

    <x-input.group inline for="subject" label="Subject" :error="$errors->first('subject')">
        <x-input.text wire:model.defer="subject" id="subject" placeholder="Subject"></x-input.text>
    </x-input.group>

    <x-input.group inline for="content" label="Content" :error="$errors->first('content')">
        <x-input.textarea wire:model.defer="content" id="content" placeholder="Content" rows="18"></x-input.textarea>
    </x-input.group>
</div>

resources/views/livewire/extra-items-form.blade.php
<div>
    <div class="mt-2 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-5">
        <div class="sm:col-span-2">
            <x-input.group inline for="description" :error="$errors->first('description')">
                <x-input.text wire:model.defer="description" id="description" placeholder="Description"
                ></x-input.text>
            </x-input.group>
        </div>
        <x-input.group inline for="quantity" :error="$errors->first('quantity')">
            <x-input.text wire:model.defer="quantity" id="quantity" placeholder="Quantity"
            ></x-input.text>
        </x-input.group>
        <x-input.group inline for="amount" :error="$errors->first('amount')">
            <x-input.text wire:model.defer="amount" id="amount" placeholder="Price"
            ></x-input.text>
        </x-input.group>
        <x-button.primary class="mt-1" wire:click="addItem">
            <svg class="-ml-2 mr-1 h-5 w-5 text-white" x-description="Heroicon name: plus" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M10 5a1 1 0 011 1v3h3a1 1 0 110 2h-3v3a1 1 0 11-2 0v-3H6a1 1 0 110-2h3V6a1 1 0 011-1z" clip-rule="evenodd"></path>
            </svg>
            Add
        </x-button.primary>
    </div>

    <div class="mt-2 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-5">
        @foreach($extraItems as $item)
            <div class="sm:col-span-2">
                <p>{{$item['description']}}</p>
            </div>
            <p class="text-right">{{$item['quantity']}}</p>
            <p class="text-right">$ {{$item['amount']}}</p>
            <x-button class="mt-1 bg-red-700" wire:click="removeItem({{$loop->index}})">
                <svg class="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path></svg>
            </x-button>
        @endforeach
    </div>
</div>

resources/views/livewire/orders.blade.php
<div>
    <h1 class="text-2xl font-semibold text-gray-900">Orders</h1>

    <div class="py-4 space-y-4">
        <div class="flex justify-between">
            <div class="flex space-x-4 w-2/4">
                <div class="w-1/2">
                    <x-input.text wire:model="filters.search" placeholder="Search Company / Reference..." />
                </div>
                <x-button.link wire:click="$toggle('showFilters')">@if ($showFilters) Hide @endif Advanced Search
                </x-button.link>
            </div>
            <div class="space-x-2 lg:flex items-center">
                <x-input.group borderless paddingless for="perPage" label="Per Page">
                    <x-input.select wire:model="perPage" id="perPage">
                        <option value="10">10</option>
                        <option value="25">25</option>
                        <option value="50">50</option>
                    </x-input.select>
                </x-input.group>
            </div>
        </div>

        <div>
            @if ($showFilters)
            <div class="bg-gray-200 p-4 rounded shadow-inner lg:flex relative">
                <div class="w-1/2 pr-2 space-y-4">
                    <x-input.group inline for="filter-tenant" label="Company">
                        <x-input.select wire:model="filters.tenant" id="filter-tenant">
                            <option value="" disabled>Select Company...</option>
                            @foreach (auth()->user()->isTenant() ? auth()->user()->tenants : \App\Models\Tenant::all() as $tenant)
                                <option value="{{ $tenant->id }}">{{ $tenant->name }}</option>
                            @endforeach
                        </x-input.select>
                    </x-input.group>

                    <x-input.group inline for="filter-status" label="Status">
                        <x-input.select wire:model="filters.status" id="filter-status">
                            <option value="" disabled>Select Status...</option>

                            @foreach (App\Models\Order::STATUSES as $value => $label)
                            <option value="{{ $value }}">{{ $label }}</option>
                            @endforeach
                        </x-input.select>
                    </x-input.group>
                </div>

                <div class="w-1/2 pr-2 space-y-4">
                    <x-input.group inline for="filter-amount-min" label="Minimum Amount">
                        <x-input.money wire:model.lazy="filters.amount-min" id="filter-amount-min" />
                    </x-input.group>


                    <x-input.group inline for="filter-amount-max" label="Maximum Amount">
                        <x-input.money wire:model.lazy="filters.amount-max" id="filter-amount-max" />
                    </x-input.group>
                </div>

                <div class="w-1/2 pr-2 space-y-4">
                    <x-input.group inline for="filter-date-min" label="Minimum Date">
                        <x-input.date wire:model="filters.date-min" id="filter-date-min" placeholder="MM/DD/YYYY" />
                    </x-input.group>

                    <x-input.group inline for="filter-date-max" label="Maximum Date">
                        <x-input.date wire:model="filters.date-max" id="filter-date-max" placeholder="MM/DD/YYYY" />
                    </x-input.group>
                </div>

                <div class="w-1/2 pr-2 space-y-4">
                    <x-button.link wire:click="resetFilters" class="absolute right-0 bottom-0 p-4">Reset Filters
                    </x-button.link>
                </div>
            </div>
            @endif

        </div>

        <!-- Orders Table -->
        <div class="flex-col space-y-4">
            <x-table>
                <x-slot name="head">
                    <x-table.heading class="pr-0 w-8">
                        @if (count($orders))
                            <x-input.checkbox wire:model="selectPage" />
                        @endif
                    </x-table.heading>
                    <x-table.heading sortable multi-column wire:click="sortBy('tenants.name')" :direction="$sorts['tenants.name'] ?? null">Company
                    </x-table.heading>
                    <x-table.heading sortable multi-column wire:click="sortBy('users.name')" :direction="$sorts['users.name'] ?? null">Staff
                    </x-table.heading>
                    <x-table.heading sortable multi-column wire:click="sortBy('reference')" :direction="$sorts['reference'] ?? null">Reference
                    </x-table.heading>
                    <x-table.heading sortable multi-column wire:click="sortBy('product')" :direction="$sorts['product'] ?? null">Product
                    </x-table.heading>
                    <x-table.heading sortable multi-column wire:click="sortBy('amount')" :direction="$sorts['amount'] ?? null">Amount
                    </x-table.heading>
                    <x-table.heading sortable multi-column wire:click="sortBy('status')" :direction="$sorts['status'] ?? null">Status
                    </x-table.heading>
                    <x-table.heading sortable multi-column wire:click="sortBy('eta')" :direction="$sorts['eta'] ?? null">ETA
                    </x-table.heading>
                    <x-table.heading sortable multi-column wire:click="sortBy('created_at')" :direction="$sorts['created_at'] ?? null">Date
                    </x-table.heading>
                    <x-table.heading />
                </x-slot>

                <x-slot name="body">
                    @if ($selectPage)
                    <x-table.row class="bg-gray-200" wire:key="row-message">
                        <x-table.cell colspan="8">
                            @unless ($selectAll)
                            <div>
                                <span>You have selected <strong>{{ $orders->count() }}</strong> orders, do you want to select all <strong>{{ $orders->total() }}</strong>?</span>
                                <x-button.link wire:click="selectAll" class="ml-1 text-blue-600">Select All
                                </x-button.link>
                            </div>
                            @else
                            <span>You are currently selecting all <strong>{{ $orders->total() }}</strong> orders.</span>
                            @endif
                        </x-table.cell>
                    </x-table.row>
                    @endif

                    @forelse ($orders as $order)
                    <x-table.row wire:loading.class.delay="opacity-50" wire:key="row-{{ $order->id }}">
                        <x-table.cell class="pr-0">
                            <x-input.checkbox wire:model="selected" value="{{ $order->id }}" />
                        </x-table.cell>

                        <x-table.cell>
                            <span class="inline-flex space-x-2 truncate text-sm leading-5">

                                <span class="text-gray-600 truncate font-medium">
                                    {{ $order->tenant->name }}
                                </span>
                            </span>
                        </x-table.cell>

                        <x-table.cell>
                            <span class="text-gray-600 font-medium">{{ $order->staff->name }} </span>
                        </x-table.cell>

                        <x-table.cell>
                            <span class="text-gray-600 font-medium">{{ $order->reference }} </span>
                        </x-table.cell>


                        <x-table.cell>
                            <span class="text-gray-600 font-medium">{{ $order->product }} </span>
                        </x-table.cell>

                        <x-table.cell>
                            <span class="text-gray-600 font-medium">$ {{ $order->amount }} </span>
                        </x-table.cell>

                        <x-table.cell>
                            <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium leading-4 bg-{{ $order->status_colour }}-100 text-{{ $order->status_colour }}-800 capitalize">
                                {{ $order->status }}
                            </span>
                        </x-table.cell>

                        <x-table.cell>
                            <span class="text-gray-600 font-medium">{{ $order->eta ? $order->eta->format('d/m/Y') : null }} </span>
                        </x-table.cell>

                        <x-table.cell>
                            <span class="text-gray-600 font-medium"> {{ $order->date_for_humans }} </span>
                        </x-table.cell>

                        <x-table.cell>
                            @can('update', \App\Models\Order::class)
                            <x-button.link wire:click="edit({{ $order->id }})">
                                <x-icon.edit />
                            </x-button.link>
                            @endcan
                        </x-table.cell>
                    </x-table.row>
                    @empty
                    <x-table.row>
                        <x-table.cell colspan="8">
                            <div class="flex justify-center items-center space-x-2">
                                <x-icon.inbox class="h-8 w-8 text-gray-400" />
                                <span class="font-medium py-8 text-gray-400 text-xl">No Orders found...</span>
                            </div>
                        </x-table.cell>
                    </x-table.row>
                    @endforelse
                </x-slot>
            </x-table>

            <div>
                {{ $orders->links() }}
            </div>
        </div>
    </div>

    <!-- Save Product Discount Modal -->
    <form wire:submit.prevent="save">
        <x-modal.dialog wire:model.defer="showEditModal">
            <x-slot name="title">Edit Order</x-slot>
            <x-slot name="content">
                <x-input.group for="status" label="Status" :error="$errors->first('editing.status')">
                    <x-input.select wire:model.defer="editing.status" id="status" placeholder="Please Select...">
                        @foreach($editing->getStatuses() as $label)
                            <option value="{{$label}}">{{ucfirst($label)}}</option>
                        @endforeach
                    </x-input.select>
                </x-input.group>
                <x-input.group for="eta" label="ETA" :error="$errors->first('editing.eta_for_editing')">
                    <x-input.date wire:model.defer="editing.eta_for_editing" id="eta" placeholder="DD/MM/YYYY"></x-input.date>
                </x-input.group>
            </x-slot>
            <x-slot name="footer">
                <x-button.secondary wire:click="$set('showEditModal', false)">Cancel</x-button.secondary>
                <x-button.primary type="submit">Save</x-button.primary>
            </x-slot>
        </x-modal.dialog>
    </form>
</div>